server:
  port: 8501 #端口号

spring:
  datasource: #MySQL数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  data:
    redis: #Redis数据库连接
      host: localhost
      port: 6379
  jackson: #json时间的时区-响应给前端的数据
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 100MB #单个文件的最大值，默认1MB
      max-request-size: 1000MB #一个请求中所有文件的总大小，默认10MB


mybatis: #MyBatis配置
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml

#自定义配置
spzx:
  auth:
    noAuthUrls: #不需要拦截的路径
      - /admin/system/index/login
      - /admin/system/index/getCaptcha
      - /doc.html
      - /v3/api-docs/**
      - /error
      - /webjars/**
      - /favicon.ico
  minio: #minio服务端
    endpoint: http://localhost:9000
    accessKey: admin
    secretKey: 12345678
    bucket: spzx-bucket